enablePSP: false

persistence:
    defaultClass: false

longhornUI:
    replicas: 1

longhornConversionWebhook:
    replicas: 1

longhornAdmissionWebhook:
    replicas: 1

longhornRecoveryBackend:
    replicas: 1

preUpgradeChecker:
    jobEnabled: false

ingress:
    enabled: true
    ingressClassName: nginx
    host: "longhorn.${OPERATIONS_DOMAIN}"
    tls: true
    tlsSecret: origin-cert

metrics:
    serviceMonitor:
        enabled: false
