alertmanager:
    alertmanagerSpec:
        resources:
            requests:
                cpu: "100m"
                memory: "128Mi"
            limits:
                cpu: "150m"
                memory: "192Mi"

prometheusOperator:
    resources:
        requests:
            cpu: "100m"
            memory: "128Mi"
        limits:
            cpu: "150m"
            memory: "192Mi"

prometheus:
    prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        ruleSelectorNilUsesHelmValues: false
        resources:
            requests:
                cpu: "500m"
                memory: "1024Mi"
            limits:
                cpu: "750m"
                memory: "1536Mi"

additionalPrometheusRulesMap:
    rule-name:
        groups:
            - name: longhorn.rules
              rules:
                  - alert: LonghornVolumeActualSpaceUsedWarning
                    annotations:
                        description:
                            The actual space used by Longhorn volume {{$labels.volume}} on {{$labels.node}} is at {{$value}}% capacity for
                            more than 5 minutes.
                        summary: The actual used space of Longhorn volume is over 90% of the capacity.
                    expr: (longhorn_volume_actual_size_bytes / longhorn_volume_capacity_bytes) * 100 > 90
                    for: 5m
                    labels:
                        issue: The actual used space of Longhorn volume {{$labels.volume}} on {{$labels.node}} is high.
                        severity: warning
                  - alert: LonghornVolumeStatusCritical
                    annotations:
                        description:
                            Longhorn volume {{$labels.volume}} on {{$labels.node}} is Fault for
                            more than 2 minutes.
                        summary: Longhorn volume {{$labels.volume}} is Fault
                    expr: longhorn_volume_robustness == 3
                    for: 5m
                    labels:
                        issue: Longhorn volume {{$labels.volume}} is Fault.
                        severity: critical
                  - alert: LonghornVolumeStatusWarning
                    annotations:
                        description:
                            Longhorn volume {{$labels.volume}} on {{$labels.node}} is Degraded for
                            more than 5 minutes.
                        summary: Longhorn volume {{$labels.volume}} is Degraded
                    expr: longhorn_volume_robustness == 2
                    for: 5m
                    labels:
                        issue: Longhorn volume {{$labels.volume}} is Degraded.
                        severity: warning
                  - alert: LonghornNodeStorageWarning
                    annotations:
                        description:
                            The used storage of node {{$labels.node}} is at {{$value}}% capacity for
                            more than 5 minutes.
                        summary: The used storage of node is over 70% of the capacity.
                    expr: (longhorn_node_storage_usage_bytes / longhorn_node_storage_capacity_bytes) * 100 > 70
                    for: 5m
                    labels:
                        issue: The used storage of node {{$labels.node}} is high.
                        severity: warning
                  - alert: LonghornDiskStorageWarning
                    annotations:
                        description:
                            The used storage of disk {{$labels.disk}} on node {{$labels.node}} is at {{$value}}% capacity for
                            more than 5 minutes.
                        summary: The used storage of disk is over 70% of the capacity.
                    expr: (longhorn_disk_usage_bytes / longhorn_disk_capacity_bytes) * 100 > 70
                    for: 5m
                    labels:
                        issue: The used storage of disk {{$labels.disk}} on node {{$labels.node}} is high.
                        severity: warning
                  - alert: LonghornNodeDown
                    annotations:
                        description: There are {{$value}} Longhorn nodes which have been offline for more than 5 minutes.
                        summary: Longhorn nodes is offline
                    expr: (avg(longhorn_node_count_total) or on() vector(0)) - (count(longhorn_node_status{condition="ready"} == 1) or on() vector(0)) > 0
                    for: 5m
                    labels:
                        issue: There are {{$value}} Longhorn nodes are offline
                        severity: critical
                  - alert: LonghornInstanceManagerCPUUsageWarning
                    annotations:
                        description:
                            Longhorn instance manager {{$labels.instance_manager}} on {{$labels.node}} has CPU Usage / CPU request is {{$value}}% for
                            more than 5 minutes.
                        summary: Longhorn instance manager {{$labels.instance_manager}} on {{$labels.node}} has CPU Usage / CPU request is over 300%.
                    expr: (longhorn_instance_manager_cpu_usage_millicpu/longhorn_instance_manager_cpu_requests_millicpu) * 100 > 300
                    for: 5m
                    labels:
                        issue: Longhorn instance manager {{$labels.instance_manager}} on {{$labels.node}} consumes 3 times the CPU request.
                        severity: warning
                  - alert: LonghornNodeCPUUsageWarning
                    annotations:
                        description:
                            Longhorn node {{$labels.node}} has CPU Usage / CPU capacity is {{$value}}% for
                            more than 5 minutes.
                        summary: Longhorn node {{$labels.node}} experiences high CPU pressure for more than 5m.
                    expr: (longhorn_node_cpu_usage_millicpu / longhorn_node_cpu_capacity_millicpu) * 100 > 90
                    for: 5m
                    labels:
                        issue: Longhorn node {{$labels.node}} experiences high CPU pressure.
                        severity: warning

kubeScheduler:
    enabled: false

kubeControllerManager:
    enabled: false

grafana:
    enabled: true
    forceDeployDatasources: true
    forceDeployDashboards: true

    datasources:
        datasources.yaml:
            apiVersion: 1
            datasources:
                - name: Loki
                  type: loki
                  access: proxy
                  url: http://loki-gateway.loki
                  jsonData:
                      httpHeaderName1: "X-Scope-OrgID"
                  secureJsonData:
                      httpHeaderValue1: "tenant1"
    admin:
        existingSecret: "grafana-password"
        userKey: admin-user
        passwordKey: admin-password
    resources:
    limits:
        cpu: 128m
        memory: 128Mi
    requests:
        cpu: 64m
        memory: 64Mi
    grafana.ini:
        auth:
            disable_login_form: false
        auth.basic:
            enabled: true
        users:
            auto_assign_org_role: Admin
        server:
            domain: "monitor.${OPERATIONS_DOMAIN}"
            root_url: "https://monitor.${OPERATIONS_DOMAIN}"
    ingress:
        enabled: true
        hosts:
            - "monitor.${OPERATIONS_DOMAIN}"
        path: "/"
        ingressclassName: nginx
        tls:
            - secretName: origin-cert
              hosts:
                  - "monitor.${OPERATIONS_DOMAIN}"
        annotations:
            kubernetes.io/ingress.class: nginx
    extraVolumeMounts: []
    dashboardProviders:
        default.yaml:
            apiVersion: 1
            providers:
                - name: "default"
                  folder: "logging"
                  type: file
                  updateIntervalSeconds: 10
                  options:
                      path: /var/lib/grafana/dashboards
    dashboards:
        default:
            loki-kubernetes-logs:
                json: |
                    {
                      "annotations": {
                        "list": [
                          {
                            "builtIn": 1,
                            "datasource": {
                              "type": "datasource",
                              "uid": "grafana"
                            },
                            "enable": true,
                            "hide": true,
                            "iconColor": "rgba(0, 211, 255, 1)",
                            "name": "Annotations & Alerts",
                            "target": {
                              "limit": 100,
                              "matchAny": false,
                              "tags": [],
                              "type": "dashboard"
                            },
                            "type": "dashboard"
                          }
                        ]
                      },
                      "description": "Logs collected from Kubernetes, stored in Loki",
                      "editable": true,
                      "fiscalYearStartMonth": 0,
                      "gnetId": 15141,
                      "graphTooltip": 0,
                      "id": 1,
                      "links": [],
                      "liveNow": false,
                      "panels": [
                        {
                          "datasource": {
                            "type": "loki",
                            "uid": "P8E80F9AEF21F6940"
                          },
                          "description": "",
                          "fieldConfig": {
                            "defaults": {
                              "color": {
                                "mode": "palette-classic"
                              },
                              "custom": {
                                "axisCenteredZero": false,
                                "axisColorMode": "text",
                                "axisLabel": "",
                                "axisPlacement": "auto",
                                "barAlignment": 0,
                                "drawStyle": "bars",
                                "fillOpacity": 0,
                                "gradientMode": "none",
                                "hideFrom": {
                                  "legend": false,
                                  "tooltip": false,
                                  "viz": false
                                },
                                "lineInterpolation": "linear",
                                "lineWidth": 1,
                                "pointSize": 5,
                                "scaleDistribution": {
                                  "type": "linear"
                                },
                                "showPoints": "auto",
                                "spanNulls": false,
                                "stacking": {
                                  "group": "A",
                                  "mode": "none"
                                },
                                "thresholdsStyle": {
                                  "mode": "off"
                                }
                              },
                              "mappings": [],
                              "thresholds": {
                                "mode": "absolute",
                                "steps": [
                                  {
                                    "color": "green",
                                    "value": null
                                  },
                                  {
                                    "color": "red",
                                    "value": 80
                                  }
                                ]
                              }
                            },
                            "overrides": []
                          },
                          "gridPos": {
                            "h": 4,
                            "w": 24,
                            "x": 0,
                            "y": 0
                          },
                          "id": 4,
                          "options": {
                            "legend": {
                              "calcs": [],
                              "displayMode": "list",
                              "placement": "bottom",
                              "showLegend": false
                            },
                            "tooltip": {
                              "mode": "single",
                              "sort": "none"
                            }
                          },
                          "targets": [
                            {
                              "datasource": {
                                "type": "loki",
                                "uid": "P8E80F9AEF21F6940"
                              },
                              "expr": "sum(count_over_time({namespace=~\"$namespace\", stream=~\"$stream\", container =~\"$container\"} |= \"$query\" [$__interval]))",
                              "instant": false,
                              "legendFormat": "Log count",
                              "range": true,
                              "refId": "A"
                            }
                          ],
                          "type": "timeseries"
                        },
                        {
                          "datasource": {
                            "type": "loki",
                            "uid": "P8E80F9AEF21F6940"
                          },
                          "description": "Logs from services running in Kubernetes",
                          "gridPos": {
                            "h": 25,
                            "w": 24,
                            "x": 0,
                            "y": 4
                          },
                          "id": 2,
                          "options": {
                            "dedupStrategy": "none",
                            "enableLogDetails": true,
                            "prettifyLogMessage": true,
                            "showCommonLabels": true,
                            "showLabels": true,
                            "showTime": true,
                            "sortOrder": "Descending",
                            "wrapLogMessage": true
                          },
                          "targets": [
                            {
                              "datasource": {
                                "type": "loki",
                                "uid": "P8E80F9AEF21F6940"
                              },
                              "expr": "{namespace=~\"$namespace\", stream=~\"$stream\", container =~\"$container\"} |= \"$query\"",
                              "refId": "A"
                            }
                          ],
                          "type": "logs"
                        }
                      ],
                      "refresh": false,
                      "schemaVersion": 37,
                      "style": "dark",
                      "tags": [],
                      "templating": {
                        "list": [
                          {
                            "current": {
                              "selected": false,
                              "text": "",
                              "value": ""
                            },
                            "description": "String to search for",
                            "hide": 0,
                            "label": "Search Query",
                            "name": "query",
                            "options": [
                              {
                                "selected": true,
                                "text": "",
                                "value": ""
                              }
                            ],
                            "query": "",
                            "skipUrlSync": false,
                            "type": "textbox"
                          },
                          {
                            "allValue": ".+",
                            "current": {
                              "selected": false,
                              "text": "All",
                              "value": "$__all"
                            },
                            "datasource": {
                              "type": "loki",
                              "uid": "P8E80F9AEF21F6940"
                            },
                            "definition": "label_values(namespace)",
                            "hide": 0,
                            "includeAll": true,
                            "multi": true,
                            "name": "namespace",
                            "options": [],
                            "query": "label_values(namespace)",
                            "refresh": 1,
                            "regex": "",
                            "skipUrlSync": false,
                            "sort": 0,
                            "type": "query"
                          },
                          {
                            "allValue": ".+",
                            "current": {
                              "selected": false,
                              "text": "All",
                              "value": "$__all"
                            },
                            "datasource": {
                              "type": "loki",
                              "uid": "P8E80F9AEF21F6940"
                            },
                            "definition": "label_values(stream)",
                            "hide": 0,
                            "includeAll": true,
                            "multi": true,
                            "name": "stream",
                            "options": [],
                            "query": "label_values(stream)",
                            "refresh": 1,
                            "regex": "",
                            "skipUrlSync": false,
                            "sort": 0,
                            "type": "query"
                          },
                          {
                            "allValue": ".+",
                            "current": {
                              "selected": false,
                              "text": "All",
                              "value": "$__all"
                            },
                            "datasource": {
                              "type": "loki",
                              "uid": "P8E80F9AEF21F6940"
                            },
                            "definition": "label_values(container)",
                            "hide": 0,
                            "includeAll": true,
                            "multi": true,
                            "name": "container",
                            "options": [],
                            "query": "label_values(container)",
                            "refresh": 1,
                            "regex": "",
                            "skipUrlSync": false,
                            "sort": 0,
                            "type": "query"
                          }
                        ]
                      },
                      "time": {
                        "from": "now-6h",
                        "to": "now"
                      },
                      "timepicker": {},
                      "timezone": "",
                      "title": "Loki Kubernetes Logs",
                      "uid": "o6-BGgnnk",
                      "version": 2,
                      "weekStart": ""
                    }
