configs:
  cm:
    create: false
  secret:
    createSecret: false

  params:
    server.insecure: true

global:
  domain: "argocd.${OPERATIONS_DOMAIN}"

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - "argocd.${OPERATIONS_DOMAIN}"
    paths:
      - /
    tls:
      - secretName: origin-cert
        hosts:
          - "argocd.${OPERATIONS_DOMAIN}"
