configs:
  cm:
    create: false
  secret:
    createSecret: false

  params:
    server.insecure: true

global:
  domain: "${ARGOCD_DOMAIN}"

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - "${ARGOCD_DOMAIN}"
    paths:
      - /
    tls:
      - secretName: origin-cert
        hosts:
          - "${ARGOCD_DOMAIN}"
