deploymentMode: SingleBinary

global:
    clusterDomain: "${PRIMARY_DOMAIN}"

singleBinary:
    replicas: 1

    persistence:
        enableStatefulSetAutoDeletePVC: true
    extraVolumeMounts:
        - name: loki-working-directory
          mountPath: /opt/working_directory
    extraVolumes:
        - name: loki-working-directory
          persistentVolumeClaim:
              claimName: loki-working-directory
    resources:
        limits:
            cpu: 1000m
            memory: 2Gi
        requests:
            cpu: 250m
            memory: 512Mi

    affinity:
        podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution: []

backend:
    replicas: 0
read:
    replicas: 0
write:
    replicas: 0

ingester:
    replicas: 0
querier:
    replicas: 0
queryFrontend:
    replicas: 0
queryScheduler:
    replicas: 0
distributor:
    replicas: 0
compactor:
    replicas: 0
indexGateway:
    replicas: 0
bloomCompactor:
    replicas: 0
bloomGateway:
    replicas: 0

gateway:
    enabled: true

    basicAuth:
        enabled: false
    resources:
        limits:
            cpu: 150m
            memory: 192Mi
        requests:
            cpu: 100m
            memory: 128Mi

    affinity:
        podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution: []

monitoring:
    selfMonitoring:
        enable: true
        grafanaAgent:
            installOperator: false
    lokiCanary:
        resources:
            limits:
                cpu: 200m
                memory: 256Mi
            requests:
                cpu: 50m
                memory: 64Mi

loki:
    auth_enabled: false

    commonConfig:
        replication_factor: 1

    limits_config:
        allow_structured_metadata: true
        volume_enabled: true
        retention_period: 168h

    schemaConfig:
        configs:
            - from: 2024-11-01
              object_store: filesystem
              store: tsdb
              schema: v13
              index:
                  prefix: index_
                  period: 24h

    storage_config:
        filesystem:
            directory: /opt/working_directory

    ingester:
        chunk_encoding: snappy
    pattern_ingester:
        enabled: true

    ruler:
        enable_api: true

    compactor:
        working_directory: /opt/working_directory
        compaction_interval: 10m
        retention_enabled: true
        retention_delete_delay: 2h
        retention_delete_worker_count: 150
        delete_request_store: filesystem

    querier:
        max_concurrent: 4

    tracing:
        enabled: true

    storage:
        type: filesystem

extraObjects:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
          name: loki-working-directory
          labels:
              app.kubernetes.io/component: single-binary
              app.kubernetes.io/instance: loki
              app.kubernetes.io/name: loki
          namespace: loki
      spec:
          accessModes:
              - ReadWriteOnce
          resources:
              requests:
                  storage: 10Gi
          storageClassName: standard
