image:
    pullPolicy: IfNotPresent
    repository: "docker.io"
    image: zimagi/knowledge-interface
    tag: "${KNOWLEDGE_INTERFACE_TAG}"

deployment:
    env:
        KNOWLEDGE_ADMIN_PROTOCOL: http
        KNOWLEDGE_ADMIN_HOSTNAME: api.knowledge-admin
        KNOWLEDGE_ADMIN_PORT: 8080

        QDRANT_HTTPS: false
        QDRANT_HOSTNAME: "qdrant.qdrant"
        QDRANT_PORT: 6333

    livenessProbe:
        endpoint: "/"

    readinessProbe:
        endpoint: "/"

services:
    ui:
        deployment:
            replicaCount: 1
            nodeSelector:
                node-role: ui
            resources:
                requests:
                    cpu: "50m"
                    memory: "256Mi"

        annotations:
            configmap.reloader.stakater.com/reload: global
            secret.reloader.stakater.com/reload: global
            cert-manager.io/cluster-issuer: cert-issuer

        ingress:
            enabled: true
            className: nginx-ui
            hosts:
                - host: "${PRIMARY_DOMAIN}"
            tls:
                - secretName: ui-cert
