image:
    pullPolicy: Never
    repository: ""
    image: knowledge_interface
    tag: dev

volumes:
    host:
        /app:
            name: app-source
            path: "${__knowledge_interface_project_dir}"

deployment:
    env:
        KNOWLEDGE_ADMIN_PROTOCOL: http
        KNOWLEDGE_ADMIN_HOSTNAME: api.knowledge-admin
        KNOWLEDGE_ADMIN_PORT: 8080

        QDRANT_HTTPS: false
        QDRANT_HOSTNAME: "qdrant.qdrant"
        QDRANT_PORT: 6333

    port: 4321

    livenessProbe:
        endpoint: "/"

    readinessProbe:
        endpoint: "/"

services:
    ui:
        deployment:
            resources:
                requests:
                    cpu: "100m"
                    memory: "100Mi"

        annotations:
            configmap.reloader.stakater.com/reload: global
            secret.reloader.stakater.com/reload: global

        ingress:
            enabled: true
            className: nginx
            hosts:
                - host: "${PRIMARY_DOMAIN}"
            tls:
                - secretName: origin-cert
